name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node (uses version from .nvmrc)
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          # Removed 'cache: pnpm' from here, as it's not for pnpm executable caching.

      - name: Extract PNPM version from package.json
        id: pnpm_version
        # This step extracts the pnpm version from the 'packageManager' field in package.json.
        # Ensure your package.json has a line like: "packageManager": "pnpm@8.15.6"
        run: echo "version=$(jq -r '.packageManager' package.json | cut -d'@' -f2)" >> "$GITHUB_OUTPUT"

      - name: Setup pnpm ${{ steps.pnpm_version.outputs.version }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ steps.pnpm_version.outputs.version }}
          # Removed 'cache: pnpm' from here, as this action does not accept a 'cache' input.
          # The action manages its own internal caching or doesn't require explicit caching
          # for the pnpm executable itself.

      - name: Verify pnpm installation
        # This step checks if pnpm is correctly installed and available in the PATH.
        # If pnpm is not found, this step will fail, helping to debug the issue.
        run: pnpm --version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm run build
